image:
  tag: ${image_tag}
host: ${host}
replicaCount: ${app_replicas}.0
minAvailable: 1
externalMongodbUrl: ${mongodb_uri}
externalMongodbOplogUrl: ${mongodb_oplog_uri}
smtp:
  enabled: true
  host: ${smtp_host}
  port: ${smtp_port}
  username: ${smtp_username}
  password: ${smtp_password}

resources:
  limits:
    cpu: 1000m
    memory: 2000Mi
  requests:
    cpu: 750m
    memory: 1500Mi

mongodb:
  enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 5M
  path: "/"
  tls:
    - hosts:
        - ${host}
      secretName: ${tls_secret_name}
