image:
  tag: ${image_tag}

ingress:
  public:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: ${host}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - ${host}
        secretName: ${tls_secret_name}

kratos:
  autoMigrate: true

  config:
    dsn: ${dsn}

    serve:
      public:
        base_url: https://${host}
        cors:
          # TODO: is this even doing anything? Since we proxy via frontend anyways
          enabled: true
          allowed_origins:
            # TODO: only in staging
            - http://127.0.0.1:3000/
            # TODO: var
            - https://*.serlo-staging.dev
            # TODO: only in staging
            - https://*.serlo.vercel.app
            # TODO: delete after tests
            - https://frontend-gf5944wgn-serlo.vercel.app
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
          allowed_headers:
            - Authorization
            - Cookie
          exposed_headers:
            - Content-Type
            - Set-Cookie

    selfservice:
      default_browser_return_url: http://127.0.0.1:3000/

      methods:
        password:
          enabled: true

      flows:
        error:
          ui_url: http://127.0.0.1:3000/error

        settings:
          ui_url: http://127.0.0.1:3000/settings
          privileged_session_max_age: 15m

        recovery:
          enabled: true
          ui_url: http://127.0.0.1:3000/recovery

        verification:
          enabled: true
          ui_url: http://127.0.0.1:3000/verify
          after:
            default_browser_return_url: http://127.0.0.1:3000/

        logout:
          after:
            default_browser_return_url: http://127.0.0.1:3000/login

        login:
          ui_url: http://127.0.0.1:3000/login
          lifespan: 10m

        registration:
          lifespan: 10m
          ui_url: http://127.0.0.1:3000/registration
          after:
            password:
              hooks:
                - hook: session

    secrets:
      cookie:
        - ${cookie_secret}

    identity:
      default_schema_id: default
      schemas:
            - id: default
              url: https://serlo.org/auth/kratos-identity.schema.json

    courier:
      smtp:
        connection_uri: smtp://SMTP_Injection:${smtp_password}@smtp.eu.sparkpostmail.com:2525
        from_name: Serlo
        from_address: no-reply@mail.serlo.org

deployment:
  resources:
    limits:
      cpu: 80m
      memory: 256Mi
    requests:
      cpu: 40m
      memory: 128Mi
