image:
  tag: ${image_tag}

ingress:
  public:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: ${host}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - ${host}
        secretName: ${tls_secret_name}

kratos:
  autoMigrate: true

  config:
    dsn: ${dsn}

    serve:
      public:
        base_url: https://${host}
        cors:
          enabled: true
          allowed_origins:
            # TODO: only in staging
            - http://localhost:3000/
            # TODO: var
            - https://*.serlo-staging.dev
            # TODO: only in staging
            - https://*.serlo.vercel.app
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
          allowed_headers:
            - Authorization
            - Cookie
            - X-CSRF-Token
          exposed_headers:
            - Content-Type
            - Set-Cookie
            - X-CSRF-Token

    selfservice:
      default_browser_return_url: https://kratos-vercel.serlo-staging.dev/

      methods:
        password:
          enabled: true
        link:
          enabled: true
          config:
            base_url: https://kratos-vercel.serlo-staging.dev/api/.ory/

      flows:
        error:
          ui_url: https://kratos-vercel.serlo-staging.dev/auth/error

        settings:
          ui_url: https://kratos-vercel.serlo-staging.dev/auth/settings
          privileged_session_max_age: 15m

        recovery:
          enabled: true
          ui_url: https://kratos-vercel.serlo-staging.dev/auth/recovery

        verification:
          enabled: true
          ui_url: https://kratos-vercel.serlo-staging.dev/auth/verification
          after:
            default_browser_return_url: https://kratos-vercel.serlo-staging.dev/auth/login

        logout:
          after:
            default_browser_return_url: https://kratos-vercel.serlo-staging.dev/auth/login

        login:
          ui_url: https://kratos-vercel.serlo-staging.dev/auth/login
          lifespan: 10m

        registration:
          lifespan: 10m
          ui_url: https://kratos-vercel.serlo-staging.dev/auth/registration
          after:
            hooks:
              - hook: web_hook
                config:
                  url: https://api.${domain}/kratos/register
                  method: POST
                  body: https://${domain}/auth/after-registration-hook-payload.jsonnet
                  auth:
                    type: api_key
                    config:
                      name: x-kratos-key
                      value: ${kratos_secret}
                      in: header

    secrets:
      cookie:
        - ${cookie_secret}

    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: https://${domain}/auth/kratos-identity.schema.json

    courier:
      smtp:
        connection_uri: smtp://SMTP_Injection:${smtp_password}@smtp.eu.sparkpostmail.com:2525
        from_name: Serlo
        from_address: no-reply@mail.serlo.org
      # TODO: just for testing purpose, remove hard code
      template_override_path: https://kratos-vercel.${domain}/api/.ory/mail-templates
      templates:
        verification:
          valid:
            email:
              subject: http://kratos-vercel.${domain}/api/.ory/mail-templates/verification/valid/email.subject.gotmpl
              body:
                html: http://kratos-vercel.${domain}/api/.ory/mail-templates/verification/valid/email.body.gotmpl
                plaintext: http://kratos-vercel.${domain}/api/.ory/mail-templates/verification/valid/email.body.plaintext.gotmpl
          invalid:
            email:
              subject: http://kratos-vercel.${domain}/api/.ory/mail-templates/verification/invalid/email.subject.gotmpl
              body:
                html: http://kratos-vercel.${domain}/api/.ory/mail-templates/verification/invalid/email.body.gotmpl
                plaintext: http://kratos-vercel.${domain}/api/.ory/mail-templates/verification/invalid/email.body.plaintext.gotmpl
        recovery:
          valid:
            email:
              subject: http://kratos-vercel.${domain}/api/.ory/mail-templates/recovery/valid/email.subject.gotmpl
              body:
                html: http://kratos-vercel.${domain}/api/.ory/mail-templates/recovery/valid/email.body.gotmpl
                plaintext: http://kratos-vercel.${domain}/api/.ory/mail-templates/recovery/valid/email.body.plaintext.gotmpl
          invalid:
            email:
              subject: http://kratos-vercel.${domain}/api/.ory/mail-templates/recovery/invalid/email.subject.gotmpl
              body:
                html: http://kratos-vercel.${domain}/api/.ory/mail-templates/recovery/invalid/email.body.gotmpl
                plaintext: http://kratos-vercel.${domain}/api/.ory/mail-templates/recovery/invalid/email.body.plaintext.gotmpl
deployment:
  resources:
    limits:
      cpu: 80m
      memory: 256Mi
    requests:
      cpu: 40m
      memory: 128Mi
