image:
  tag: ${image_tag}

ingress:
  public:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: ${host}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - ${host}
        secretName: ${tls_secret_name}
kratos:
  autoMigrate: true

  config:
    dsn: ${dsn}

    serve:
      public:
        base_url: https://${host}
        cors:
          # TODO: is this even doing anything? Since we proxy via frontend anyways
          # TODO: as suspected, this is not doing anything at all. Instead, we'd need to configure Ingress
          enabled: true
          allowed_origins:
            # TODO: only in staging
            - http://127.0.0.1:3000/
            # TODO: var
            - https://*.serlo-staging.dev
            # TODO: only in staging
            - https://*.serlo.vercel.app
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
          allowed_headers:
            - Authorization
            - Cookie
          exposed_headers:
            - Content-Type
            - Set-Cookie
      admin:
        base_url: http://kratos-admin.${namespace}:4445

    selfservice:
      default_browser_return_url: http://frontend.serlo-staging.dev/
      whitelisted_return_urls:
        - http://frontend.serlo-staging.dev

      methods:
        oidc:
          enabled: true
          config:
            providers:
              - id: github
                provider: github
                client_id: ${github_client_id}
                client_secret: ${github_client_secret}
                mapper_url: https://serlo.org/auth/kratos-github.jsonnet
                scope:
                  - user:email

        password:
          enabled: true

      flows:
        error:
          ui_url: http://frontend.serlo-staging.dev/error

        settings:
          ui_url: http://frontend.serlo-staging.dev/settings
          privileged_session_max_age: 15m

        recovery:
          enabled: true
          ui_url: http://frontend.serlo-staging.dev/recovery

        verification:
          enabled: true
          ui_url: http://frontend.serlo-staging.dev/verify
          after:
            default_browser_return_url: http://frontend.serlo-staging.dev/

        logout:
          after:
            default_browser_return_url: http://frontend.serlo-staging.dev/login

        login:
          ui_url: http://frontend.serlo-staging.dev/login
          lifespan: 10m

        registration:
          lifespan: 10m
          ui_url: http://frontend.serlo-staging.dev/registration
          after:
            password:
              hooks:
                - hook: session

    secrets:
      cookie:
        - ${cookie_secret}

    identity:
      default_schema_url: https://serlo.org/auth/kratos-identity.schema.json

    courier:
      smtp:
        connection_uri: smtp://SMTP_Injection:${smtp_password}@smtp.eu.sparkpostmail.com:2525
        from_name: Serlo
        from_address: no-reply@mail.serlo.org

deployment:
  resources:
    limits:
      cpu: 40m
      memory: 128Mi
    requests:
      cpu: 20m
      memory: 64Mi
