image:
  tag: ${image_tag}

ingress:
  public:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: ${host}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - ${host}
        secretName: ${tls_secret_name}

kratos:
  autoMigrate: true

  config:
    dsn: ${dsn}

    serve:
      public:
        base_url: https://${host}
        cors:
          enabled: true
          allowed_origins:
            # TODO: only in staging
            - http://localhost:3000/
            # TODO: var
            - https://*.serlo-staging.dev
            # TODO: only in staging
            - https://*.serlo.vercel.app
            # TODO: delete after tests
            - https://frontend-gf5944wgn-serlo.vercel.app
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
          allowed_headers:
            - Authorization
            - Cookie
            - X-CSRF-Token
          exposed_headers:
            - Content-Type
            - Set-Cookie
            - X-CSRF-Token

    selfservice:
      default_browser_return_url: http://localhost:3000/

      methods:
        password:
          enabled: true
        link:
          enabled: true
          config:
            base_url: http://localhost:3000
      flows:
        error:
          ui_url: http://localhost:3000/auth/error

        settings:
          ui_url: http://localhost:3000/auth/settings
          privileged_session_max_age: 15m

        recovery:
          enabled: true
          ui_url: http://localhost:3000/auth/recovery

        verification:
          enabled: true
          ui_url: http://localhost:3000/auth/verification
          after:
            default_browser_return_url: http://localhost:3000/auth/login

        logout:
          after:
            default_browser_return_url: http://localhost:3000/auth/login

        login:
          ui_url: http://localhost:3000/auth/login
          lifespan: 10m

        registration:
          lifespan: 10m
          ui_url: http://localhost:3000/auth/registration
          after:
            hooks:
              - hook: web_hook
                config:
                  url: https://api.${domain}/kratos/register
                  method: POST
                  body: https://${domain}/auth/after-registration-hook-payload.jsonnet

    secrets:
      cookie:
        - ${cookie_secret}

    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: https://${domain}/auth/kratos-identity.schema.json

    courier:
      smtp:
        connection_uri: smtp://SMTP_Injection:${smtp_password}@smtp.eu.sparkpostmail.com:2525
        from_name: Serlo
        from_address: no-reply@mail.serlo.org

deployment:
  resources:
    limits:
      cpu: 80m
      memory: 256Mi
    requests:
      cpu: 40m
      memory: 128Mi
