image:
  tag: ${image_tag}
  repository: eu.gcr.io/serlo-shared/kratos
ingress:
  public:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: ${host}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - ${host}
        secretName: ${tls_secret_name}

kratos:
  autoMigrate: true

  config:
    dsn: ${dsn}

    serve:
      public:
        base_url: https://${host}
        request_log:
          disable_for_health: true
      admin:
        request_log:
          disable_for_health: true
    selfservice:
      default_browser_return_url: https://${domain}/
      allowed_return_urls:
        # TODO: try with wildcard later
        - https://fr.${domain}/
        - https://hi.${domain}/
        - https://de.${domain}/
        - https://ta.${domain}/
        - https://en.${domain}/
        - https://es.${domain}/
      methods:
        password:
          enabled: true
          config:
            haveibeenpwned_enabled: false
        link:
          enabled: true
          config:
            base_url: https://${domain}/api/.ory/
        oidc:
          enabled: true
          config:
            providers:
              - id: nbp
                provider: generic
                client_id: serlo
                # TODO: pass as secret
                client_secret: "****"
                issuer_url: https://aai-dev.nbpdev.de/realms/nbp-aai
                mapper_url: base64://${mapper}

      flows:
        error:
          ui_url: https://${domain}/auth/error

        settings:
          ui_url: https://${domain}/auth/settings
          privileged_session_max_age: 15m

        recovery:
          enabled: true
          use: link
          ui_url: https://${domain}/auth/recovery

        verification:
          enabled: true
          use: link
          ui_url: https://${domain}/auth/verification

        logout:
          after:
            default_browser_return_url: https://${domain}/auth/login

        login:
          ui_url: https://${domain}/auth/login
          lifespan: 10m
          after:
            password:
              hooks:
                - hook: require_verified_address

        registration:
          lifespan: 10m
          ui_url: https://${domain}/auth/registration
          after:
            hooks:
              - hook: web_hook
                config:
                  url: https://api.${domain}/kratos/register
                  method: POST
                  body: https://${domain}/auth/after-registration-hook-payload.jsonnet
                  auth:
                    type: api_key
                    config:
                      name: x-kratos-key
                      value: ${kratos_secret}
                      in: header

    session:
      lifespan: 720h

    secrets:
      cookie:
        - ${cookie_secret}

    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: https://${domain}/auth/kratos-identity.schema.json

    courier:
      smtp:
        connection_uri: smtp://SMTP_Injection:${smtp_password}@smtp.eu.sparkpostmail.com:2525
        from_name: Serlo
        from_address: no-reply@mail.serlo.org
      # TODO: just for testing purpose, remove hard code
      template_override_path: https://${domain}/api/.ory/mail-templates
      templates:
        verification:
          valid:
            email:
              subject: http://${domain}/api/.ory/mail-templates/verification/valid/email.subject.gotmpl
              body:
                html: http://${domain}/api/.ory/mail-templates/verification/valid/email.body.gotmpl
                plaintext: http://${domain}/api/.ory/mail-templates/verification/valid/email.body.plaintext.gotmpl
          invalid:
            email:
              subject: http://${domain}/api/.ory/mail-templates/verification/invalid/email.subject.gotmpl
              body:
                html: http://${domain}/api/.ory/mail-templates/verification/invalid/email.body.gotmpl
                plaintext: http://${domain}/api/.ory/mail-templates/verification/invalid/email.body.plaintext.gotmpl
        recovery:
          valid:
            email:
              subject: http://${domain}/api/.ory/mail-templates/recovery/valid/email.subject.gotmpl
              body:
                html: http://${domain}/api/.ory/mail-templates/recovery/valid/email.body.gotmpl
                plaintext: http://${domain}/api/.ory/mail-templates/recovery/valid/email.body.plaintext.gotmpl
          invalid:
            email:
              subject: http://${domain}/api/.ory/mail-templates/recovery/invalid/email.subject.gotmpl
              body:
                html: http://${domain}/api/.ory/mail-templates/recovery/invalid/email.body.gotmpl
                plaintext: http://${domain}/api/.ory/mail-templates/recovery/invalid/email.body.plaintext.gotmpl
deployment:
  resources:
    limits:
      cpu: 80m
      memory: 256Mi
    requests:
      cpu: 40m
      memory: 128Mi
